### ISSUE TITLE
Documentation on how to train and predict 

### ISSUE THREAD

**Issue by ghost** [ResearchingDexter/TinyMind-RMB-Recognition#1]
@ResearchingDexter Thank you for your hard work

Documentation on how to train and predict

**Comment by ghost** [comment]
@ResearchingDexter

**Comment by ResearchingDexter** [comment]
Thanks for your attention, I have added the docs for the code, you can train and predict refer to the **docs** . If you have other problems, please ask. @deepseek

**Comment by ghost** [comment]
Still, can you add further step-by-step details on how to train detection and recognition.
perhaps even what structure the dataset for training should be.
I want to see the potential of your code.
waiting for your reply

**Comment by ResearchingDexter** [comment]
The code aims at the picture with horizonal arbitrary length textlines and recognize the textlines. You need to train the detection and recognition model **separately**. In the train phase, train the detection model according to the coordinates in the train set and crop the textlines according to the coordinates to train the recognition model. In the test phase, integrate them(i.e. **firstly** detection the location of the textlines using the detection model; **secondly** crop the textlines according to the coordinates that are from the detection model; **finally** recognize the textlines using the recognition model)
